pydocs
borisborelly/michar pull request #4
Opened 2024-01-21 03:06 UTC by borisborelly

i didn't realize until after i churned this out that we can't use gh pages as a private repo

maybe we should IPO

2024-01-21 03:48 UTC, borisborelly commented on docs/app.rst
> +   :nested: full
this is how the sphinx doc generation works for click apps

2024-01-21 03:49 UTC, borisborelly commented on docs/conf.py
> +extensions = ['sphinx_click.ext', "sphinx.ext.autodoc", "sphinx.ext.coverage","sphinx.ext.napoleon",'sphinx.ext.intersphinx']
sphinx extentions / setup follow here

2024-01-21 03:50 UTC, borisborelly commented on docs/index.html
> +    </img src="michar_logo.jpeg" alt="michar number one" width="400" height="400">
i propose a meeting to sort out a logo (and actually make it show up, mine doesnt work cus im dumb)

2024-01-21 03:50 UTC, borisborelly commented on src/michar/__init__.py
> +__copyright__ = '2024, Boris, Rob'
pay us

2024-01-21 18:36 UTC, rpuncel commented
> maybe we should IPO

I don't mind, wasn't sure if you made private for a specific reason. Then we can also do SonarCloud :D

2024-01-21 18:36 UTC, rpuncel commented on docs/index.html
> +    </img src="michar_logo.jpeg" alt="michar number one" width="400" height="400">
Send me an invite

2024-01-21 18:49 UTC, rpuncel requested changes
Some small questions, feel free to open up new issue for any you don't want to do right now

2024-01-21 18:49 UTC, rpuncel commented on docs/michar/_sources/michar/michar.api.rst.txt
Two questions:

1. Is this file (and all others in _sources and _static) auto-generated?
2. What branch are you planning on using to host github pages if you get that going?

If answer to #1 is yes and answer to #2 is a `gh-pages` or other dedicated branch, these should be removed and go in the .gitigore

2024-01-21 18:49 UTC, rpuncel commented on docs/index.html
> +    </img src="michar_logo.jpeg" alt="michar number one" width="400" height="400">
Created new issue to track logo https://github.com/borisborelly/michar/issues/5

2024-01-21 18:49 UTC, rpuncel commented on tox.ini
> +[testenv:pydocs]
Want to add a quick blurb to README? or do we want to make an issue to rev up the `make help`

2024-01-21 18:49 UTC, rpuncel commented on tox.ini
> +    sphinx-build -b html -d docs/build/doctrees ./docs docs/michar
Works on my machine

2024-01-21 18:49 UTC, rpuncel commented on tox.ini
Do you want to give adding `tox -e pydoc` to check that the docs build to the github actions build workflow? Or I can add it. I think it will be quick either way, I just think we should add it at the same time

2024-01-22 04:33 UTC, borisborelly commented on docs/michar/_sources/michar/michar.api.rst.txt
1. yeah @rpuncel the FILES in `./docs` is the source and everything in a DIRECTORY under `./docs` is generated
2. i was going to stuff it in our `develop` for now because I don't feel like figuring out the auto-update to `gh-pages` . I created #11 for this

2024-01-22 04:37 UTC, borisborelly commented on tox.ini
> +[testenv:pydocs]
I added something to README and captured something for `Makefile` in #12

2024-01-22 04:37 UTC, borisborelly commented on tox.ini
I created #11 for this

2024-01-22 04:48 UTC, merged